directories:
  output: release
  buildResources: build
appId: com.vconecty.app
productName: VConectY
extraResources:
  - from: electron/worker.exe
    to: worker.exe
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target:
    - target: portable
      arch:
        - x64
  icon: icon.ico
portable:
  artifactName: VConectY-Portable.exe
compression: maximum
electronVersion: 25.9.8
